# config.py

CRT_HTF = "H1"
CRT_LTF = "M1"

CRT_ATR_PERIOD = 14
CRT_RANGE_MULT = 1.2
CRT_MAX_RANGE_MULT = 3.0
CRT_BODY_RATIO = 0.6

CRT_TTL_HOURS = 6

# TBS
TBS_MAX_MINUTES_AFTER_SWEEP = 15
TBS_SL_ATR_BUFFER_MULT = 0.1
TBS_MAX_RISK_ATR_H1_MULT = 1.2
